---
title: "Reconstruct a contrast map"
author: "Junhui He"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, include = FALSE)
```

```{r}
# load package
library(oro.nifti)
library(neurobase)
library(EBARS)
library(mgcv)

# file path
data_path = "G:/Phd/Data/HCPFMRI/WM_contrasts"

set.seed(1234)

# read data
index_subjects = read.csv(file.path(data_path, "index2bk-0bk.csv"))
subject_name = sample(index_subjects$subject, 1)

# read nii
contrast_map = readnii(file.path(data_path, "Contrasts", paste0(subject_name, "_2bk-0bk.nii")))
mni152 = readnii(file.path(data_path, "templates/MNI152_T1_2mm.nii"))
slice_idxs = ceiling(dim(mni152)/2)

# test mse
test_mses = array(NA, dim = c(3,3))
```


```{r}
# coronal, sagittal, axial
ortho2(mni152, xyz = slice_idxs, crosshairs = FALSE)
```


## Sagittal

```{r}
set.seed(1234)
# process slices
idx_slice = slice_idxs[1]
contrast_slice = contrast_map[idx_slice,,]

slice_array_na = cbind(expand.grid(1:dim(contrast_slice)[1], 1:dim(contrast_slice)[2]), c(contrast_slice))
slice_array = slice_array_na[!is.na(slice_array_na[,3]),]

# normalize locations
x = as.matrix(slice_array[,1:2])
for (i in 1:2) {
  x[,i] = (x[,i] - min(x[,i])) / (max(x[,i]) - min(x[,i]))
}
y = slice_array[,3]

m_train = floor(0.8 * length(y))
train_idx = sample.int(length(y), m_train)
```


Run ABMRS algorithm to detect activated voxel

```{r}
# apply EBARS
model_bebars = binebars(x[train_idx,], y[train_idx], k_1=10, k_2=10, n_1=1000, n_2=1000)

time_start = Sys.time()
model_bebars$mcmc(burns=1000, steps=1000)
time_end = Sys.time()
print(time_end - time_start)
```

```{r}
# fit a spline model
knots_sag = model_bebars$knots()
save(knots_sag, file = "knots_sag.RData")
z = tensor_spline(x, xi_1=knots_sag$xi_1, xi_2=knots_sag$xi_2)
reg_df = as.data.frame(z)
reg_df$y = y
lm_model = lm(y ~ ., data=reg_df, subset = train_idx)

# compute predictive intervals
pred_int = as.data.frame(predict(lm_model, reg_df, interval="prediction", level=0.999))

# compute test mse
test_mses[1,1] = mean((pred_int$fit - y)[-train_idx]^2)
# Thin Plate Spline
x_train_df = data.frame(x1 = x[train_idx,1], x2 = x[train_idx,2])
x_new_df = data.frame(x1 = x[-train_idx,1], x2 = x[-train_idx,2])
model_tps = gam(y[train_idx]~s(x1, x2, k = 150), data = x_train_df)
y_tps = predict(model_tps,x_new_df)
test_mses[2,1] = mean((y[-train_idx]-y_tps)^2)
# Tensor Product Spline
model_tep = gam(y[train_idx]~te(x1, x2, k = 15), data = x_train_df)
y_tep = predict(model_tep, x_new_df)
test_mses[3,1] = mean((y[-train_idx]-y_tep)^2)
```


## Coronal

```{r}
set.seed(1234)
# process slices
idx_slice = slice_idxs[2]
contrast_slice = contrast_map[,idx_slice,]

slice_array_na = cbind(expand.grid(1:dim(contrast_slice)[1], 1:dim(contrast_slice)[2]), c(contrast_slice))
slice_array = slice_array_na[!is.na(slice_array_na[,3]),]

# normalize locations
x = as.matrix(slice_array[,1:2])
for (i in 1:2) {
  x[,i] = (x[,i] - min(x[,i])) / (max(x[,i]) - min(x[,i]))
}
y = slice_array[,3]

m_train = floor(0.8 * length(y))
train_idx = sample.int(length(y), m_train)
```

Run ABMRS algorithm to detect activated voxel

```{r}
# apply EBARS
model_bebars = binebars(x[train_idx,], y[train_idx], k_1=10, k_2=10, n_1=1000, n_2=1000)

time_start = Sys.time()
model_bebars$mcmc(burns=1000, steps=1000)
time_end = Sys.time()
print(time_end - time_start)
```

```{r}
# fit a spline model
knots_cor = model_bebars$knots()
save(knots_cor, file = "knots_cor.RData")
z = tensor_spline(x, xi_1=knots_cor$xi_1, xi_2=knots_cor$xi_2)
reg_df = as.data.frame(z)
reg_df$y = y
lm_model = lm(y ~ ., data=reg_df, subset = train_idx)

# compute predictive intervals
pred_int = as.data.frame(predict(lm_model, reg_df, interval="prediction", level=0.999))

# compute test mse
test_mses[1,2] = mean((pred_int$fit - y)[-train_idx]^2)
# Thin Plate Spline
x_train_df = data.frame(x1 = x[train_idx,1], x2 = x[train_idx,2])
x_new_df = data.frame(x1 = x[-train_idx,1], x2 = x[-train_idx,2])
model_tps = gam(y[train_idx]~s(x1, x2, k = 150), data = x_train_df)
y_tps = predict(model_tps,x_new_df)
test_mses[2,2] = mean((y[-train_idx]-y_tps)^2)
# Tensor Product Spline
model_tep = gam(y[train_idx]~te(x1, x2, k = 15), data = x_train_df)
y_tep = predict(model_tep, x_new_df)
test_mses[3,2] = mean((y[-train_idx]-y_tep)^2)
```

## Axial

```{r}
set.seed(1234)
# process slices
idx_slice = slice_idxs[3]
contrast_slice = contrast_map[,,idx_slice]

slice_array_na = cbind(expand.grid(1:dim(contrast_slice)[1], 1:dim(contrast_slice)[2]), c(contrast_slice))
slice_array = slice_array_na[!is.na(slice_array_na[,3]),]

# normalize locations
x = as.matrix(slice_array[,1:2])
for (i in 1:2) {
  x[,i] = (x[,i] - min(x[,i])) / (max(x[,i]) - min(x[,i]))
}
y = slice_array[,3]

m_train = floor(0.8 * length(y))
train_idx = sample.int(length(y), m_train)
```

Run ABMRS algorithm to detect activated voxel

```{r}
# apply EBARS
model_bebars = binebars(x[train_idx,], y[train_idx], k_1=10, k_2=10, n_1=1000, n_2=1000)

time_start = Sys.time()
model_bebars$mcmc(burns=1000, steps=1000)
time_end = Sys.time()
print(time_end - time_start)
```

```{r}
# fit a spline model
knots_axi = model_bebars$knots()
save(knots_cor, file = "knots_axi.RData")
z = tensor_spline(x, xi_1=knots_axi$xi_1, xi_2=knots_axi$xi_2)
reg_df = as.data.frame(z)
reg_df$y = y
lm_model = lm(y ~ ., data=reg_df, subset = train_idx)

# compute predictive intervals
pred_int = as.data.frame(predict(lm_model, reg_df, interval="prediction", level=0.999))

# compute test mse
test_mses[1,3] = mean((pred_int$fit - y)[-train_idx]^2)
# Thin Plate Spline
x_train_df = data.frame(x1 = x[train_idx,1], x2 = x[train_idx,2])
x_new_df = data.frame(x1 = x[-train_idx,1], x2 = x[-train_idx,2])
model_tps = gam(y[train_idx]~s(x1, x2, k = 150), data = x_train_df)
y_tps = predict(model_tps,x_new_df)
test_mses[2,3] = mean((y[-train_idx]-y_tps)^2)
# Tensor Product Spline
model_tep = gam(y[train_idx]~te(x1, x2, k = 15), data = x_train_df)
y_tep = predict(model_tep, x_new_df)
test_mses[3,3] = mean((y[-train_idx]-y_tep)^2)
```


Save MSE

```{r}
save(test_mses, file = "test_mses.RData")
```




