---
title: "Peak detection in surface fitting"
author: "Junhui He"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# load package
library(ABMRS)
```

```{r}
# define functions
f1 <- function(x) {
  y = -40*(exp(-10*(x[,1]-0.3)^2-10*(x[,2]-0.3)^2) - exp(-10*(x[,1]-0.7)^2-10*(x[,2]-0.7)^2))
  return(y)
}

# plot contour
grid = seq(0, 1, by = 0.01)
contour(x=grid,y=grid,z=outer(grid,grid,function(x,y) {return(f1(cbind(x,y)))}),axes = TRUE,frame.plot =TRUE)
```

```{r}
f1_scalar <- function(x) {
  y = -40*(exp(-10*(x[1]-0.3)^2-10*(x[2]-0.3)^2) - exp(-10*(x[1]-0.7)^2-10*(x[2]-0.7)^2))
  return(y)
}

p_1 = optim(c(0.3, 0.3), f1_scalar)$par
p_2 = optim(c(0.7, 0.7), f1_scalar, control = list(fnscale = -1))$par

p_1 # （0.2864, 0.2864）
p_2 # (0.7136, 0.7136)
```

# Posterior Distributions of the Number of Knots

```{r}
set.seed(1234)

# generate training samples
ms = c(150, 260, 500)
for (m in ms) {
  x = cbind(runif(m), runif(m))
  y = f1(x)
  y_obs = y + rnorm(m, 0, 1)
  xmin = c(0,0); xmax = c(1,1)

  # run surface ABMRS
  my_mebars = mebars(x, y_obs, xmin = xmin, xmax = xmax, gamma = 1, times = c(2,2), degrees = c(1,1))
  my_mebars$rjmcmc(burns = 20000, steps = 20000)

  knots = my_mebars$knots()
  nums_1 = sapply(knots, function(k) {length(k[[1]])})
  nums_2 = sapply(knots, function(k) {length(k[[2]])})

  num_min_1 = min(nums_1); num_max_1 = max(nums_1)
  num_min_2 = min(nums_2); num_max_2 = max(nums_2)
  p1 = ggplot(mapping=aes(x=nums_1)) + geom_bar(aes(y=after_stat(prop)), width = 0.6) + labs(x="Number of Knots", y="Proportion") + geom_vline(aes(xintercept=mean(nums_1)), color="red", linetype="dashed") + theme_classic() + theme(axis.title = element_text(size = 14)) + scale_x_continuous(breaks = seq(num_min_1-1, num_max_1+1), limits = c(num_min_1-1.2, num_max_1+1.2))
  p2 = ggplot(mapping=aes(x=nums_2)) + geom_bar(aes(y=after_stat(prop)), width = 0.6) + labs(x="Number of Knots", y="Proportion") + geom_vline(aes(xintercept=mean(nums_2)), color="red", linetype="dashed") + theme_classic() + theme(axis.title = element_text(size = 14)) + scale_x_continuous(breaks = seq(num_min_2-1, num_max_2+1), limits = c(num_min_2-1.2, num_max_2+1.2))
  
  pdf(file=file.path("figures/peak_dectection",paste0("surface_peak_m_",m,".pdf")), width=8, height=4)
  print(ggarrange(p1, p2, ncol=2, nrow=1, align="hv"))
  dev.off()
}
```

```{r}
set.seed(1234)
kms = list(c(3,3), c(3,3), c(4,5))

ks = c(4,5)
m = 500
x = cbind(runif(m), runif(m))
y = f1(x)
y_obs = y + rnorm(m, 0, 1)
xmin = c(0,0); xmax = c(1,1)

# run surface ABMRS
my_mebars = mebars(x, y_obs, xmin = xmin, xmax = xmax, ks = ks, times = c(2,2), degrees = c(1,1))
my_mebars$rjmcmc(burns = 20000, steps = 20000)

knots = my_mebars$knots()
xis_1 = sapply(knots, function(k) {k[[1]]})
xis_2 = sapply(knots, function(k) {k[[2]]})
xi_1 = rowMeans(xis_1)
xi_2 = rowMeans(xis_2)

xis = as.matrix(expand.grid(xi_1, xi_2))
is_peak = array(NA, c(nrow(xis), 2))
for (j in 1:nrow(xis)) {
  xi = xis[j, ]
  x_neigh = as.matrix(expand.grid(seq(xi[1]-0.02, xi[1]+0.02, 0.01), 
                        seq(xi[2]-0.02, xi[2]+0.02, 0.01)))
  pred = my_mebars$predict(rbind(xi, x_neigh))
  y_hat = rowMeans(pred)
  
  is_peak[j, 1] = y_hat[1] == min(y_hat)
  is_peak[j, 2] = y_hat[1] == max(y_hat)
}

peak_df = data.frame(xis, is_peak)
colnames(peak_df) = c("x_1", "x_2", "min", "max")
```

```{r}
knots = my_mebars$knots()
xis_1 = sapply(knots, function(k) {k[[1]]})
xis_2 = sapply(knots, function(k) {k[[2]]})
xi_1 = rowMeans(xis_1)
xi_2 = rowMeans(xis_2)

xis = as.matrix(expand.grid(xi_1, xi_2))
is_peak = array(NA, c(nrow(xis), 2))
for (j in 1:nrow(xis)) {
  xi = xis[j, ]
  x_neigh = as.matrix(expand.grid(seq(xi[1]-0.02, xi[1]+0.02, 0.01), 
                        seq(xi[2]-0.02, xi[2]+0.02, 0.01)))
  pred = my_mebars$predict(rbind(xi, x_neigh))
  y_hat = rowMeans(pred)
  
  is_peak[j, 1] = y_hat[1] == min(y_hat)
  is_peak[j, 2] = y_hat[1] == max(y_hat)
}

peak_df = data.frame(xis, is_peak)
colnames(peak_df) = c("x_1", "x_2", "min", "max")
```

# Peak Detection

```{r}
# run surface ABMRS
my_mebars = mebars(x, y_obs, xmin = xmin, xmax = xmax, ks = c(5,5), times = c(2,2), degrees = c(1,1))
my_mebars$rjmcmc(burns = 20000, steps = 20000)
```

```{r}
knots = my_mebars$knots()
l = length(knots)

peak_samples = list()

time_start = Sys.time()
for (i in 1:l) {
  xi_1 = knots[[i]][[1]]; xi_2 = knots[[i]][[2]]
  # fit linear spline regression
  z = tensor_spline(x, xis = list(xi_1, xi_2), degrees = c(1,1), intercepts = c(TRUE,TRUE), xmin = xmin, xmax = xmax)
  reg_df = data.frame(z, y = y_obs)
  lm_model = lm(y ~ ., data = reg_df)
  
  xis = as.matrix(expand.grid(xi_1, xi_2))
  is_peak = array(NA, c(nrow(xis), 2))
  y_pred = rep(NA, nrow(xis))
  for (j in 1:nrow(xis)) {
    xi = xis[j, ]
    x_neigh = as.matrix(expand.grid(seq(xi[1]-0.02, xi[1]+0.02, 0.01), 
                          seq(xi[2]-0.02, xi[2]+0.02, 0.01)))
    z_hat = tensor_spline(rbind(xi, x_neigh), xis = list(xi_1, xi_2), degrees = c(1,1), intercepts = c(TRUE,TRUE), xmin = xmin, xmax = xmax)
    y_hat = predict(lm_model, data.frame(z_hat))
    
    is_peak[j, 1] = y_hat[1] == min(y_hat)
    is_peak[j, 2] = y_hat[1] == max(y_hat)
    y_pred[j] = y_hat[1]
  }
  
  peak_df = data.frame(xis, is_peak, y_pred)
  colnames(peak_df) = c("x_1", "x_2", "min", "max", "y_hat")
  
  peak_samples[[i]] = peak_df
}
time_end = Sys.time()
print(time_end - time_start)
```

```{r}
# peak points
p_1 = c(0.2864, 0.2864); p_2 = c(0.7136, 0.7136)

neg_peak_points = list(); pos_peak_points = list()
peak_count = array(NA, c(l, 2))

for (i in 1:l) {
  peak_df = peak_samples[[i]]
  # negative peak
  neg_peak = as.matrix(peak_df[peak_df[,3]==1, c(1:2,5)])
  neg_peak_points[[i]] = neg_peak
  peak_count[i, 1] = nrow(neg_peak)
  
  # positive peak
  pos_peak = as.matrix(peak_df[peak_df[,4]==1, c(1:2,5)])
  pos_peak_points[[i]] = pos_peak
  peak_count[i, 2] = nrow(pos_peak)
}
```

```{r}
negative_peaks = c(); positive_peaks = c()
for (i in 1:l) {
  if (peak_count[i,1]>0) {
    neg_peak = neg_peak_points[[i]]
    negative_peaks = rbind(negative_peaks, neg_peak[which.min(neg_peak[,3]),])
  }
  if (peak_count[i,2]>0) {
    pos_peak = pos_peak_points[[i]]
    positive_peaks = rbind(positive_peaks, pos_peak[which.max(pos_peak[,3]),])
  }
}

phat_1 = colMeans(negative_peaks[,1:2])
phat_2 = colMeans(positive_peaks[,1:2])
d_1 = sqrt(sum((phat_1 - p_1)^2))
d_2 = sqrt(sum((phat_2 - p_2)^2))
cat("Negative peak distance:", d_1, "\n")
cat("Positive peak distance:", d_2, "\n")
phat_1
phat_2
```



# TODO

```{r}
set.seed(1234)

# peak points
p_1 = c(0.2864, 0.2864); p_2 = c(0.7136, 0.7136)

# experimental hyper-parameters
m = 500; num_exps = 50
peaks = list()

t_start = Sys.time()

for (k in 1:num_exps) {

t_1 = Sys.time()
cat(paste0("The ", k, "-th experiment:\t"))
# generate training samples
x = cbind(runif(m), runif(m))
y = f1(x)
y_obs = y + rnorm(m, 0, 0.8)


# run surface EBARS
my_binebars = binebars(x, y_obs, gamma = 1, n_1 = 1000, n_2 = 1000, degree_1 = 1, degree_2 = 1)
my_binebars$mcmc(burns = 1000, steps = 500)

knots = my_binebars$samples()
l = length(knots$xi_1)

peak_samples = list()

for (i in 1:l) {
  xi_1 = knots$xi_1[[i]]; xi_2 = knots$xi_2[[i]]
  # fit a linear spline regression model
  z = tensor_spline(x, xi_1, xi_2, degree_1 = 1, degree_2 = 1, intercept_1 = TRUE, intercept_2 = TRUE)
  reg_df = data.frame(z, y = y_obs)
  lm_model = lm(y ~ ., data = reg_df)
  
  # classify whether a knot is a peak point
  xis = as.matrix(expand.grid(xi_1, xi_2))
  is_peak = array(NA, c(nrow(xis), 2))
  for (j in 1:nrow(xis)) {
    xi = xis[j, ]
    x_neigh = as.matrix(expand.grid(seq(max(0, xi[1]-0.05), min(1, xi[1]+0.05), 0.005), 
                          seq(max(0, xi[2]-0.05), min(1, xi[2]+0.05), 0.005)))
    z_hat = tensor_spline(rbind(xi, x_neigh), xi_1, xi_2, degree_1 = 1, degree_2 = 1, intercept_1 = TRUE, intercept_2 = TRUE)
    y_hat = predict(lm_model, data.frame(z_hat))
    
    is_peak[j, 1] = y_hat[1] == min(y_hat)
    is_peak[j, 2] = y_hat[1] == max(y_hat)
  }
  
  peak_df = data.frame(xis, is_peak)
  colnames(peak_df) = c("x_1", "x_2", "min", "max")
  
  peak_samples[[i]] = peak_df
}

neg_peak_points = list(); pos_peak_points = list()
peak_count = array(NA, c(l, 2))

for (i in 1:l) {
  peak_df = peak_samples[[i]]
  # negative peak
  neg_peak = as.matrix(peak_df[peak_df[,3]==1, 1:2])
  neg_peak_points[[i]] = neg_peak
  peak_count[i, 1] = nrow(neg_peak)
  
  # positive peak
  pos_peak = as.matrix(peak_df[peak_df[,4]==1, 1:2])
  pos_peak_points[[i]] = pos_peak
  peak_count[i, 2] = nrow(pos_peak)
}

peaks[[k]] = list("negative_peak" = neg_peak_points,
                  "positive_peak" = pos_peak_points,
                  "count" = peak_count)

t_2 = Sys.time()
print(t_2 - t_1)

}

t_end = Sys.time()
```
